create or replace TABLE CUSTOMERCALLDATA (
	DATE DATE,
	LOCATED VARCHAR(50),
	AGENT VARCHAR(50),
	INCOMINGCALLS NUMBER(38,0),
	ANSWEREDCALLS NUMBER(38,0),
	ANSWEREDRATE FLOAT,
	ABANDONEDCALLS NUMBER(38,0),
	WAITINGTIME NUMBER(38,0),
	ANSWERSPEED NUMBER(38,0),
	TALKDURATION NUMBER(38,0),
	RESOLUTIONTIME NUMBER(38,0),
	CUSTOMERSATISFACTIONRATING NUMBER(38,0)
);